<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="LAPTOP-E5JV7D1P" failures="1" tests="8" name="PasswordManagerTests.RegistrationTest" time="3.707" errors="0" timestamp="2021-08-20T09:52:52 IST" skipped="0">
  <testcase classname="PasswordManagerTests.RegistrationTest" name="invalidFullnameTest" time="0.410"/>
  <system-out/>
  <testcase classname="PasswordManagerTests.RegistrationTest" name="Clicktest" time="0.248"/>
  <system-out/>
  <testcase classname="PasswordManagerTests.RegistrationTest" name="emptyUsernameFieldTest" time="0.598"/>
  <system-out/>
  <testcase classname="PasswordManagerTests.RegistrationTest" name="emptyPasswordFieldTest" time="0.407">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at PasswordManagerTests.RegistrationTest.emptyPasswordFieldTest(RegistrationTest.java:201)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:64)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.access$000(SuiteRunner.java:28)
at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:418)
at org.testng.internal.thread.ThreadUtil.lambda$execute$0(ThreadUtil.java:64)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
]]>
    </failure>
  </testcase> <!-- emptyPasswordFieldTest -->
  <system-out/>
  <testcase classname="PasswordManagerTests.RegistrationTest" name="AlreadyExitTest" time="0.565"/>
  <system-out/>
  <testcase classname="PasswordManagerTests.RegistrationTest" name="invalidLengthPasswordLengthTest" time="0.464"/>
  <system-out/>
  <testcase classname="PasswordManagerTests.RegistrationTest" name="invalidUsernameLengthTest" time="0.462"/>
  <system-out/>
  <testcase classname="PasswordManagerTests.RegistrationTest" name="invalidUserPassTest" time="0.553"/>
  <system-out/>
</testsuite> <!-- PasswordManagerTests.RegistrationTest -->
